import os
import tempfile
import zipfile
import oracledb
from dotenv import load_dotenv

load_dotenv()

# Try to import secretmanager, handling if it's not installed yet
try:
    from google.cloud import secretmanager
except ImportError:
    secretmanager = None

def get_wallet_dir():
    # If K_SERVICE is set, we are running in Google Cloud Run
    is_cloud_run = os.environ.get('K_SERVICE') is not None
    
    if is_cloud_run:
        wallet_dir = '/tmp/wallet'
        if not os.path.exists(wallet_dir):
            os.makedirs(wallet_dir)
            
            project_id = os.environ.get('GCP_PROJECT')
            secret_id = os.environ.get('WALLET_SECRET_ID')
            
            if not project_id or not secret_id:
                raise ValueError("GCP_PROJECT and WALLET_SECRET_ID must be set when in Cloud Run.")
            
            if not secretmanager:
                raise ImportError("google-cloud-secret-manager package is required for Cloud Run.")
                
            client = secretmanager.SecretManagerServiceClient()
            # Fetch the latest version of the zip wallet
            name = f"projects/{project_id}/secrets/{secret_id}/versions/latest"
            response = client.access_secret_version(request={"name": name})
            wallet_zip_content = response.payload.data
            
            zip_path = '/tmp/wallet.zip'
            with open(zip_path, 'wb') as f:
                f.write(wallet_zip_content)
                
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(wallet_dir)
                
        return wallet_dir
    else:
        # Local development: specify where the extracted oracle wallet is
        return os.environ.get('LOCAL_WALLET_DIR', '/wallet')

def get_connection():
    wallet_dir = get_wallet_dir()
    db_user = os.environ.get('DB_USER')
    db_password = os.environ.get('DB_PASSWORD')
    db_dsn = os.environ.get('DB_DSN')  # e.g., the TNS name from tnsnames.ora
    wallet_password = os.environ.get('WALLET_PASSWORD') # May be required for mTLS in thin driver
    
    if not (db_user and db_password and db_dsn):
        raise ValueError("DB_USER, DB_PASSWORD, and DB_DSN environment variables must be set.")
        
    connection = oracledb.connect(
        user=db_user,
        password=db_password,
        dsn=db_dsn,
        config_dir=wallet_dir,
        wallet_location=wallet_dir,
        wallet_password=wallet_password
    )
    # Using autocommit for equivalent behavior or we commit manually
    connection.autocommit = False 
    return connection

def init_db():
    conn = get_connection()
    c = conn.cursor()
    
    # Oracle doesn't have IF NOT EXISTS for tables directly, so we catch the exception (ORA-00955)
    users_sql = '''
        CREATE TABLE users (
            id VARCHAR2(255) PRIMARY KEY,
            first_name VARCHAR2(255),
            username VARCHAR2(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    '''
    try:
        c.execute(users_sql)
    except oracledb.DatabaseError as e:
        error, = e.args
        if error.code != 955: # ORA-00955: name is already used by an existing object
            raise

    test_results_sql = '''
        CREATE TABLE test_results (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id VARCHAR2(255),
            test_type VARCHAR2(100),
            value NUMBER,
            unit VARCHAR2(50),
            test_date DATE,
            is_confirmed NUMBER(1) DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id)
        )
    '''
    try:
        c.execute(test_results_sql)
    except oracledb.DatabaseError as e:
        error, = e.args
        if error.code != 955:
            raise

    conn.commit()
    conn.close()

def add_user(user_id, first_name, username=""):
    conn = get_connection()
    c = conn.cursor()
    
    try:
        # Instead of INSERT OR IGNORE, we perform insert and catch IntegrityError (ORA-00001)
        c.execute('''
            INSERT INTO users (id, first_name, username) 
            VALUES (:1, :2, :3)
        ''', (user_id, first_name, username))
        conn.commit()
    except oracledb.IntegrityError:
        pass # User already exists
    finally:
        conn.close()

def get_user_by_id_or_username(identifier):
    conn = get_connection()
    c = conn.cursor()
    clean_id = identifier.lstrip('@')
    c.execute('''
        SELECT id, first_name, username, created_at 
        FROM users 
        WHERE id = :1 OR username = :2
    ''', (identifier, clean_id))
    user = c.fetchone()
    conn.close()
    if user:
        return {"id": user[0], "first_name": user[1], "username": user[2], "created_at": user[3].isoformat() if user[3] else None}
    return None

def add_test_result(user_id, test_type, value, unit, test_date, is_confirmed=False):
    conn = get_connection()
    c = conn.cursor()
    try:
        val = float(value)
    except ValueError:
        val = None # Ensure a float type for Oracle NUMBER where possible
        
    confirmed_flag = 1 if is_confirmed else 0
    c.execute('''
        INSERT INTO test_results (user_id, test_type, value, unit, test_date, is_confirmed)
        VALUES (:1, :2, :3, :4, TO_DATE(SUBSTR(:5, 1, 10), 'YYYY-MM-DD'), :6)
    ''', (user_id, test_type, val, unit, test_date, confirmed_flag))
    conn.commit()
    conn.close()

def get_test_results(user_id):
    conn = get_connection()
    c = conn.cursor()
    # Using fetchall without Row factory for simple mapping
    c.execute('SELECT id, user_id, test_type, value, unit, test_date, is_confirmed, created_at FROM test_results WHERE user_id = :1 ORDER BY test_date DESC', (user_id,))
    rows = c.fetchall()
    
    results = []
    # Manually map to dicts
    for row in rows:
        results.append({
            "id": row[0],
            "user_id": row[1],
            "test_type": row[2],
            "value": row[3],
            "unit": row[4],
            "test_date": row[5].strftime('%Y-%m-%d') if row[5] else None,
            "is_confirmed": bool(row[6]),
            "created_at": row[7].isoformat() if row[7] else None
        })
    conn.close()
    return results

def confirm_result(result_id):
    conn = get_connection()
    c = conn.cursor()
    c.execute('UPDATE test_results SET is_confirmed = 1 WHERE id = :1', (result_id,))
    conn.commit()
    conn.close()

def delete_result(result_id):
    conn = get_connection()
    c = conn.cursor()
    c.execute('DELETE FROM test_results WHERE id = :1', (result_id,))
    conn.commit()
    conn.close()
